### PR TITLE
Modifications to avoid changes in wishlist_id

### PR DESCRIPTION
**Pull request by supreeta-anand-byatnal**

### CODE REVIEW

**Comment by sohailhodarkar** [comment]
This will need to be tested. I'll get back soon. At this point, I believe that we would need to update the ```test_models.py``` and ```test_routes.py``` files too.

**Comment by sathvikabm** [comment]
hey supreeta 
so under the products model we could remove the field to deserialize in case of product update, by passing a parameter 

so 
in model.py, under class Product(db.Model): 

we could instead do def deserialize(self, data, prod_update):

if not prod_update:
            self.wishlist_id = data['wishlist_id']

so you will have to even replace all the places 
product.deserialize is called by passing 2 values in the parameter

**Comment by sathvikabm** [comment]
also in test_model.py

this line can be removed wishlist.update() 
in  def test_update_a_wishlist_product(self):

**Comment by sohailhodarkar** [comment]
Temporarily closed

**Review by sohailhodarkar — APPROVED** [review]

**Comment by sohailhodarkar** [comment]
This was precisely what was needed. I thought it would be complicated back then. Sorry for the confusion. Good to merge!

**Pull request merged**
